export const copy = {
  app: {
    name: "Minfy Resolve"
  },
  action: {
    signOut: "Sign out",
    openSearch: "Search past solutions",
    close: "Close",
    retry: "Try again",
    search: "Search",
    back: "Back",
    next: "Continue",
    saveDraft: "Save as draft",
    submitReview: "Submit for review",
    clearFilters: "Clear filters",
    viewSolution: "View solution",
    viewProfile: "View profile",
    contactSolver: "Contact the solver",
    editSolution: "Edit solution",
    previewSolution: "Preview",
    openFullSolution: "Open full solution",
    viewSolverPanel: "View solver",
    openFullProfile: "Open full profile",
    editProfile: "Edit profile",
    saveProfile: "Save profile",
    cancel: "Cancel"
  },
  submit: {
    saved: "Draft saved",
    autosaved: "Autosaved",
    saving: "Saving",
    submitSuccess: "Submitted for review",
    restore: "Restored saved draft",
    unsaved: "Unsaved changes",
    secretWarning: "Potential secret detected. Remove credentials before submitting.",
    uploadAttachment: "Upload attachment",
    attachmentSaved: "Attachment saved for scanning",
    reviewReady: "Review your solution before submitting.",
    titleLabel: "Problem title",
    problemLabel: "Problem description",
    environmentLabel: "Technical environment",
    symptomsLabel: "Symptoms",
    errorLabel: "Exact error message",
    rootCauseLabel: "Root cause",
    stepsLabel: "Resolution steps",
    preventionLabel: "Prevention and follow-up",
    codeLabel: "Code snippets",
    technologiesLabel: "Technologies",
    visibilityLabel: "Visibility",
    validation: "Complete the required fields before submitting.",
    stepProblem: "Problem",
    stepCause: "Cause and context",
    stepResolution: "Resolution",
    stepReview: "Review"
  },
  review: {
    title: "Review submitted solutions",
    queue: "Pending submissions",
    filter: "Filter submissions",
    sort: "Sort submissions",
    sortOldest: "Oldest first",
    sortNewest: "Newest first",
    noFilteredResults: "No submissions match this filter.",
    empty: "There are no solutions waiting for review.",
    approve: "Approve",
    requestChanges: "Request changes",
    reject: "Reject",
    notes: "Review notes",
    history: "Review history",
    decisionSaved: "Review decision recorded.",
    reasonRequired: "Add review notes before requesting changes or rejecting."
  },
  nav: {
    dashboard: "Home",
    search: "Search solutions",
    submit: "Log a solved problem",
    contributions: "My profile",
    drafts: "Drafts",
    reviews: "Reviews",
    people: "People",
    profile: "My profile",
    settings: "Administration"
  },
  mobile: {
    menu: "Open navigation",
    closeMenu: "Close navigation"
  },
  dashboard: {
    title: "What are you blocked on?",
    searchHint: "Describe the problem, error message, technology, or environment.",
    logPrompt: "Solved something worth sharing?",
    logAction: "Log a solved problem",
    recent: "Recent verified solutions",
    drafts: "Your drafts",
    reviews: "Awaiting your review",
    continue: "Continue where you left off",
    empty: "No verified solutions are available to you yet."
  },
  search: {
    title: "Search past solutions",
    placeholder: "Paste an error message or describe the roadblock",
    emptyTitle: "Start with the problem you are trying to solve",
    emptyBody: "Search uses past solutions that you are allowed to access.",
    filters: "Filters",
    verifiedOnly: "Verified only",
    sort: "Sort results",
    sortRelevance: "Relevance",
    sortNewest: "Most recently updated",
    generateSummary: "Generate grounded summary",
    summaryUnavailable: "Grounded summary is temporarily unavailable.",
    sources: "Sources",
    summary: "Summary of matching solutions",
    appliedQuery: "Results for",
    verifiedResults: "Showing verified solutions",
    resultCount: "Matching solutions",
    preview: "Preview solution",
    matchedPassage: "Matched passage",
    matchReasons: "Match reasons",
    matchStrength: "Match strength",
    strengthStrong: "Strong",
    strengthMedium: "Medium",
    strengthLow: "Low",
    noAnswerTitle: "No reliable match was found",
    noAnswerBody: "Add the exact error message, affected technology or environment to improve your search.",
    clear: "Clear search",
    previousPage: "Previous page",
    nextPage: "Next page"
  },
  foundation: {
    phaseLabel: "Authenticated foundation",
    localStack: "Local stack",
    statusEyebrow: "Project foundation",
    title: "Search past solutions",
    description:
      "The approved stack is starting here: React, FastAPI, PostgreSQL with pgvector, and explicit service health checks.",
    webLabel: "Web",
    webReady: "Frontend is running.",
    apiLabel: "API",
    checkingApi: "Checking API health.",
    apiReady: "API health check passed.",
    apiUnavailable: "API health check failed.",
    signedIn: "Signed in",
    dashboardNotice: "Authentication is active. Solution discovery begins in a later phase."
  },
  login: {
    title: "Sign in to the knowledge platform",
    statement: "Find the solution your company already has.",
    email: "Work email",
    password: "Password",
    submit: "Sign in",
    submitting: "Signing in",
    invalid: "We could not sign you in with those details.",
    description: "Search verified technical fixes, understand what worked, and reach the colleague who solved it.",
    accessIntro: "Use your assigned internal account to continue.",
    seededAccess: "Seeded access profiles",
    seededAccessBody: "Select a prepared internal account for local product review.",
    internalOnly: "Approved internal access only",
    emailInvalid: "Enter a valid work email address.",
    passwordInvalid: "Enter a password between 8 and 128 characters."
  },
  shell: {
    collapseNavigation: "Collapse navigation",
    expandNavigation: "Expand navigation",
    toggleTheme: "Toggle theme",
    openUserMenu: "Open user menu",
    primaryNavigation: "Primary navigation",
    mobileNavigation: "Mobile navigation",
    workspaceGroup: "Workspace",
    knowledgeGroup: "Knowledge",
    collaborationGroup: "Collaboration",
    adminGroup: "Administration",
    signedInAs: "Signed in as"
  },
  command: {
    title: "Search and commands",
    hint: "Search solutions, people, pages, or actions",
    searchAnything: "Search solutions, people, or paste an error",
    noResults: "No matching commands",
    shortcut: "Ctrl K"
  },
  page: {
    notFoundTitle: "This page is not available",
    notFoundBody: "Check the address or return to the dashboard.",
    adminTitle: "Administration",
    adminBody: "Administration tools are available to administrators only.",
    solutionTitle: "Solution details",
    solutionBody: "Open a solution from search or an approved link.",
    authoringBody: "Create and edit solution drafts in the authoring workflow.",
    reviewsBody: "Review submitted solutions that are available to you."
  },
  detail: {
    problem: "Problem",
    symptoms: "Symptoms",
    environment: "Technical environment",
    exactError: "Exact error",
    rootCause: "Root cause",
    resolution: "Resolution",
    code: "Code and commands",
    copyCode: "Copy code",
    copied: "Copied",
    attachments: "Attachments",
    reviewTimeline: "Review timeline",
    related: "Related solutions",
    technologies: "Technologies",
    verified: "Verified",
    unverified: "Unverified",
    verifiedBy: "Verified by",
    solvedBy: "Solved by",
    solverProfile: "Solver profile",
    feedbackPrompt: "Did this solution help?",
    feedbackComment: "Optional comment",
    helpful: "Helpful",
    notHelpful: "Not helpful",
    resolved: "Resolved my issue",
    feedbackSaved: "Feedback saved",
    feedbackError: "Feedback could not be saved. Try again."
  },
  profile: {
    title: "Employee profile",
    contact: "Approved contact",
    team: "Team",
    department: "Department",
    skills: "Skills",
    technologies: "Technologies",
    verifiedSolutions: "Verified solutions",
    relevantSolutions: "Relevant solutions",
    contributions: "Contributions",
    helpful: "Helpful contributions",
    emptySkills: "No skills are listed yet.",
    emptySolutions: "No verified solutions are available to you for this employee yet.",
    emptyTags: "No technologies are associated with visible verified solutions yet.",
    editHint: "Keep your approved contact handle, skills, and short bio current so colleagues know when to reach you.",
    bio: "Bio",
    contactHandle: "Contact handle",
    workEmail: "Work email",
    displayName: "Display name",
    jobTitle: "Job title",
    skillsHelp: "Separate skills with commas.",
    profileSaved: "Profile updated."
  },
  state: {
    loading: "Loading",
    comingSoon: "No records are available in this workspace.",
    permissionTitle: "You do not have access to this content",
    permissionBody: "If you need access, contact the solution owner or an administrator.",
    notFoundTitle: "This solution is not available",
    notFoundBody: "It may have been removed or you may not have access to it.",
    networkTitle: "We could not complete that request",
    networkBody: "Check your connection and try again."
  }
} as const;
